// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1inmaXPlhucYJTdhIDvNHRwnDyaK4GSs',
    appId: '1:305119674171:web:2f1ea5c912f3def3ef011e',
    messagingSenderId: '305119674171',
    projectId: 'myapp-2bcc2',
    authDomain: 'myapp-2bcc2.firebaseapp.com',
    storageBucket: 'myapp-2bcc2.appspot.com',
    measurementId: 'G-MZH4BTY6B7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaLLsskwB6uhpmC8FQv7e7bSjRoRxKvng',
    appId: '1:305119674171:android:ca39a3d1d46b4081ef011e',
    messagingSenderId: '305119674171',
    projectId: 'myapp-2bcc2',
    storageBucket: 'myapp-2bcc2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw5a7HtoHq1WsYPFkh_vhsv5HdCvJjaWU',
    appId: '1:305119674171:ios:78d7ef1544c0cb59ef011e',
    messagingSenderId: '305119674171',
    projectId: 'myapp-2bcc2',
    storageBucket: 'myapp-2bcc2.appspot.com',
    iosClientId: '305119674171-4jmgkv6fc012r7khs3vqd4f2t7u04s6f.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );
}
